### ISSUE TITLE
Game Crashing With ( libc++abi.dylib: terminating with uncaught exception of type Il2CppExceptionWrapper )

### ISSUE THREAD

**Issue by MuhammadWaqasOfficial** [googleads/googleads-mobile-unity#1073]
Game crash when admob ad call to show with  ( libc++abi.dylib: terminating with uncaught exception of type Il2CppExceptionWrapper ).
Using
- Google Mobile Ads Unity Plugin v4.1.0
- Google Mobile Ads iOS SDK 7.52.0
- Unity Version 2019.1.2
Without admob game is not crashing.

**Comment by UragayalaDeepika** [comment]
@MuhammadWaqasOfficial Can you provide us the complete stack trace? Are you able to consistently reproduce the problem on your end? Can you provide a test app the reproduces the issue?

**Comment by QuanHuynhM** [comment]
Have you found the any solution? Im getting the same error

**Comment by MuhammadWaqasOfficial** [comment]
@QuanHuynhM  in my case back then unity admob  supporting  "Google Mobile Ads iOS SDK 7.51.0" and i add  "Google Mobile Ads iOS SDK 7.52.- -" in my xcode.
Also make sure Google Mobile Ads IOS SDK version is same as in GoogleMobileAdsDependencies.XML and in xcode.
Recently i make build successfully through cocoapods procedure.
Still need help come on "anydesk" . Happy to help you.

**Comment by QuanHuynhM** [comment]
@MuhammadWaqasOfficial 
I did try according to you said. I have adjusted everything about the admob setting to 7.52, although the latest version is 7.53.1 right now, this error is the same.

Currently I am using

Google Mobile Ads Unity Plugin v4.2.0
Google Mobile Ads iOS SDK 7.53.1
Unity Version 2019.2.17

**Comment by MirHamzaHasan** [comment]
Add this in your info.plist
change key according to your app key should fix the issue 
<key>GADApplicationIdentifier</key>
<string>ca-app-pub-3940256099942544~1458002511</string>

**Comment by Sasan-Angel** [comment]
I have tried all the things that has been mentioned here but still getting the same error and crash at launch. Would you help me please?

**Comment by stowy** [comment]
Can you please provide a stacktrace? What version of Unity are you using, which platform are you building for, which device and OS version are you using?

**Comment by uit-hyo** [comment]
I am facing the same issues on Unity iOS. 
Anyone resolved the problem ? I use 
Google Mobile SDK version -> 9.0 in Podfile

App crashes after showing Ads.

**Comment by TarmoJussila** [comment]
I'm also facing this issue with Unity 2020.3.37f1 and AdMob v7.1.0. I also have several ad mediation libraries, Firebase and GameAnalytics integrated into the app.

**Comment by asadappricot** [comment]
Game crash on splash. I m using ad-mob only (no mediation).
Unity 2020.3.17f1 and AdMob 7.2.0
EnableBitcode - No
Enable SKAdNetwork to track conversions IOS 14 - implemented
Game work fine without ads.
Your help will be appreciated.

![Screenshot 2023-01-26 at 6 49 15 PM](https://user-images.githubusercontent.com/123446191/214858569-bacb2175-dffe-4f78-a95b-de34bb0d5c9f.png)
![Screenshot 2023-01-26 at 6 50 18 PM](https://user-images.githubusercontent.com/123446191/214858620-03571f9d-36da-4f52-9a31-dcc30f04e1c0.png)
