### ISSUE TITLE
Android Crashes

### ISSUE THREAD

**Issue by Hadar2018** [googleads/googleads-mobile-unity#1265]
Hello, 
On my project I'm using the latest version 5.0.1, and getting a lot of crashes.
Here's the Stacktrace: 
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextEntry(HashMap.java:851)
	at java.util.HashMap$EntryIterator.next(HashMap.java:891)
	at java.util.HashMap$EntryIterator.next(HashMap.java:890)
	at **com.google.ads.mediation.unity.UnitySingleton$UnitySingletonListener.onUnityAdsError(UnitySingleton.java:227)**
	at com.unity3d.services.ads.configuration.AdsModuleConfiguration$3.run(AdsModuleConfiguration.java:92)
	at android.os.Handler.handleCallback(Handler.java:836)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:203)
	at android.app.ActivityThread.main(ActivityThread.java:6251)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1075)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

I'm tried having a look at the code but coudn't make sense since its new to be, I believe maybe this commit:
https://github.com/googleads/googleads-mobile-android-mediation/commit/223a15fafd42f55b44ccf740ae908a25ec5afdb2
has something to do with fixing it but I'm not sure

**Comment by swtedg** [comment]
experienced the same issue on com.google.android.gms:play-services-ads 19.1.0 and com.google.ads.mediation:unity 3.4.2.1

Reverting to 19.0.1 and 3.4.2.0 resolved the issue for us

**Comment by stowy** [comment]
Thanks @Hadar2018 tracking internally with b/154824789.

**Comment by oddgames-david** [comment]
Receiving the same error across a few different devices and os versions: Samsung Galaxy A30 (a30), 3840MB RAM, Android 9

java.lang.Error: FATAL EXCEPTION [main]
Unity version     : 2018.4.12f1
Device model      : samsung SM-A305G
Device fingerprint: samsung/a30ub/a30:9/PPR1.180610.011/A305GUBU2ASJ1:user/release-keys
Caused by
  at java.util.HashMap$HashIterator.nextNode (HashMap.java:1441)
  at java.util.HashMap$EntryIterator.next (HashMap.java:1475)
  at java.util.HashMap$EntryIterator.next (HashMap.java:1473)
  at com.google.ads.mediation.unity.UnitySingleton$UnitySingletonListener.onUnityAdsError (UnitySingleton.java:227)
  at com.unity3d.services.ads.configuration.AdsModuleConfiguration$3.run (AdsModuleConfiguration.java:92)
  at android.os.Handler.handleCallback (Handler.java:873)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:7099)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:494)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:965)

**Comment by ishnu47** [comment]
Any news on this?
I'm seeing new these crashes after upgrading to com.google.ads.mediation:unity:3.4.2.1 (with com.google.android.gms:play-services-ads:19.0.0).
Should I downgrade to com.google.ads.mediation:unity:3.4.2.0?

Thanks.

**Comment by stowy** [comment]
Yes sorry this should be fixed with https://github.com/googleads/googleads-mobile-unity/pull/1290. You can get [version 2.4.3 here](https://bintray.com/google/mobile-ads-adapters-unity/GoogleMobileAdsUnityAdsMediation#files/GoogleMobileAdsUnityAdsMediation%2F2.4.3).

**Comment by ishnu47** [comment]
@stowy Sorry, but I still seeing this crash on version 2.4.3.
Could you check it again?
Thanks.

**Comment by ishnu47** [comment]
Ah sorry, my bad.
I did not force resolve to make sure the latest lib is used correctly.
