### ISSUE TITLE
Native Ads ： Visible in game and clickable, but no impressions in admob console.

### ISSUE THREAD

**Issue by umiringo** [googleads/googleads-mobile-unity#1474]
Recently, I add native ads in our game(Unity).
The ads can be seen in our game and clickable.
But it generated no impression but have many requests and some clicks.

I really can not figure out why this happened.
Is there anyone know anything about this?

Thank you very much.

**Comment by umiringo** [comment]
For more information, I check the register function, all the register successed

**Comment by somendra1221** [comment]
We are also facing the same issue, 
there are many successful native ads filled and also properly shown in game and clickable, 
but no impression in admob panel

Please provide a solution of it as soon as possible,
We searched whole internet, but no solution is found

**Comment by danirazaq** [comment]
Hello, I am facing same issue, i have check on test mode and on live device as well , native ads are showing okay but there are not impression generating on the dashboard

**Comment by NVentimiglia** [comment]
Fixed in the next release.

**Comment by Manello** [comment]
This issue is not solved, I am using the Google Mobile Ads Unity Plugin 7.1.0 together with the latest native ads addon, and I am not registering any impressions even though the full ad is visible to the user.
The ad was loaded totally fine and had no problems.

**Comment by Vasuk9** [comment]
i have same  issue.. I am using the Google Mobile Ads Unity Plugin 7.1.0 and latest native plugin.. i am getting any impressions any  changes should we add to solve this issue...
