### ISSUE TITLE
The type 'MediationExtras' conflicts with the imported type 'MediationExtras'

### ISSUE THREAD

**Issue by p0w1nd** [googleads/googleads-mobile-unity#1676]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2019.4.25f1
  * Google Mobile Ads Unity plugin version: 6.0.1
  * Platform: iOS
  * Platform OS version: iOS 14.5
  * Mediation ad networks used, and their versions: AppLovin, FAN, Vungle, Unity Ads, ironSource

### [REQUIRED] Step 2: Describe the problem

During building, Unity shows this warning:

```Assets/GoogleMobileAds/Api/Mediation/Vungle/VungleMediationExtras.cs(6,51): warning CS0436: The type 'MediationExtras' in '/Users/p0w1nd/Projects/Unity/prisonescape/Assets/GoogleMobileAds/Api/Mediation/MediationExtras.cs' conflicts with the imported type 'MediationExtras' in 'GoogleMobileAds.Core, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in '/Users/p0w1nd/Projects/Unity/prisonescape/Assets/GoogleMobileAds/Api/Mediation/MediationExtras.cs'.```

**Comment by Mecze** [comment]
Same Problem here:

- Unity version: 2020.3.15f2
- Google Mobile Ads Unity plugin version: 6.0.2
- Platform: Android
- Platform OS version: Target API 29
- Mediation ad networks used, and their versions: 

  - AdColony: version 2.3.0
  - Applovin: version 5.1.0
  - Facebook: version 3.3.1
  - InMobi: version 3.1.2
  - IronSource: version 2.1.0
  - MoPub: version 2.15.0 +SDK
  - myTarget: version 3.9.0
  - TapJoy: version 2.7.0
  - UnityAds: version 2.7.1
  - Vungle: version 3.6.0
  - Amazon APS: Aps Core 1.2.0

**Comment by Mecze** [comment]
I found a workaround:
Comment out or delete the script "Assets/GoogleMobileAds/Api/MediationExtras.cs"

**Comment by superbderrick** [comment]
@Mecze Thanks, I did equally

**Comment by Mecze** [comment]
This issue should be closed:

The culprit is the AdColony Mediation (2.3.0 on my case) that IMPORTS "Assets/GoogleMobileAds/Api/MediationExtras.cs" and it shouldn't, since Admob plugin doesn't.

Maybe another mediations do that too, I haven't check.

**Comment by YounusShalaby** [comment]
just fix the namespace of "Assets/GoogleMobileAds/Api/MediationExtras.cs"

TO (GoogleMobileAds.Api.Mediation.AdColony)
NOT (GoogleMobileAds.Api.Mediation)

**Comment by NVentimiglia** [comment]
Fixed in latest.

**Comment by shefich** [comment]
@NVentimiglia 
Doesn't fixed. I still have this error: "The type 'MediationExtras' conflicts with the imported type 'MediationExtras'" smthg. like this. Fixed as "YounusShalaby" said.
