### ISSUE TITLE
AppIDs dissapearing when changing code after implementing #1695

### ISSUE THREAD

**Issue by bigmonmulgrew** [googleads/googleads-mobile-unity#1796]
### Step 0: Are you in the right place?

  * For general technical questions, or help with project-specific issues like setting up ads in
   your app, reach out to our support team on the
   [Developer Forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/game-engines).
  * For assistance with your AdMob account, reach out to
   [AdMob Support](https://support.google.com/admob/?hl=en#topic=7383088).
  * For feedback on [our documentation](https://developers.google.com/admob/unity/start),
   send  your feedback by pressing the **Send Feedback** button at the top right of the
    documentation page you are on.
  * For issues related to __the code in this repository__, continue filing this GitHub issue.

  * Once you've read this section and determined that your issue is appropriate for
    this repository, **please delete this section**.

### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2020.3.15f2
  * Google Mobile Ads Unity plugin version: 6.1.1
  * Platform: Unity Editor (iOS, Android, Unity Editor)
  * Platform OS version: Windows 10 (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: _____

### [REQUIRED] Step 2: Describe the problem
Apop IDs dissapear when tabbing back to unity after making a change.
This appears to be the same as #1692  and #1694 
Opening a new issue since I have applied the fix in #1695 and the issue appears to be related but not identical.

#### Steps to reproduce:

1. Install the plugin
2. Apply the fix in #1695 
3. Change any code in visual studio.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by NVentimiglia** [comment]
Thanks, I will review.

**Comment by madTeddy** [comment]
Yep, that fix worked before new release with new bad code in GoogleMobileAdsSettings script.
This part of code written without testing for sure. They loading the file from the Resources and then creating a new instance.
https://github.com/googleads/googleads-mobile-unity/blob/ebd375f124375d3133e7195a80208c15c7981f21/source/plugin/Assets/GoogleMobileAds/Editor/GoogleMobileAdsSettings.cs#L50-L72

**Comment by dareerahmadmufti** [comment]
This issue is resolved in the latest plugin version "Google Mobile Ads Unity Plugin v6.1.2".

**Comment by rohitvishwakarma1819** [comment]
> To fix this, try adding another null check after line 59 in the above code, like this:
> 
> ```
>          instance = Resources.Load<GoogleMobileAdsSettings>(MobileAdsSettingsFile); 
> 
>          if (instance != null) 
>          { 
>              return instance; 
>          } 
> ```

@yerfdogj  I  have these changes, but still facing same issue

**Comment by moldovev** [comment]
I'm on 6.1.2 and the issue is present.

**Comment by kunny** [comment]
Fixed in https://github.com/googleads/googleads-mobile-unity/releases/tag/v6.1.2.
