### ISSUE TITLE
iOS Bug: Ad callbacks not triggering (reproducible)

### ISSUE THREAD

**Issue by PokerDawg** [googleads/googleads-mobile-unity#1879]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2021.2.1, 2021.1.1
  * Google Mobile Ads Unity plugin version: 6.1.2
  * Platform: iOS
  * Platform OS version: iOS 15.2, 15.1
  * Any specific devices issue occurs on: any iOS device
  * Mediation ad networks used, and their versions: none

#### Steps to reproduce:

[AdMob Event Issue (2021.2.1).zip](https://github.com/googleads/googleads-mobile-unity/files/7739601/AdMob.Event.Issue.2021.2.1.zip)

1. build and run the provided project on iOS
2. open the app and wait for AdMob to initialize and load an ad
3. press the 'Show Ad' button
4. press the X button on the interstitial test ad to close it
5. immediately open the iOS control center (swipe down from the right side of the top edge of the screen)

**Expected result:** the ad closes and the `OnAdClosed` callback is triggered
**Actual result:** the ad closes but the `OnAdClosed` callback is **NOT** triggered

Here are two videos:

- the 'control': the app can load an ad, open and close it, and all the associated callbacks function properly
https://user-images.githubusercontent.com/11318436/146649288-935c6fe7-e4de-421c-b6a2-e5708d9f70a7.mov
- the 'problem': demonstrating the bug, folowing steps 2-5 from above
https://user-images.githubusercontent.com/11318436/146649321-608ab374-c38b-4b66-a041-af0757dd691e.mov

#### Notes and findings:

- on iOS, by default, opening the control center (or notifications, or multitasking) will pause the game and make it not in focus (can be seen by using [`MonoBehaviour.OnApplicationPause`](https://docs.unity3d.com/ScriptReference/MonoBehaviour.OnApplicationPause.html) and [`MonoBehaviour.OnApplicationFocus`](https://docs.unity3d.com/ScriptReference/MonoBehaviour.OnApplicationFocus.html))
- by enabling the 'Enable Custom Background Behaviours' option (in Player Settings > Other Settings > Configuration), the game won't be paused when the control center is opened, but it will lose focus (according to the two methods from the previous point); this bug still occurs even with this option enabled
- settings the game to pause while an ad is running with `MobileAds.SetiOSAppPauseOnBackground(true);` does not solve this issue either; the same thing happens and the game remains paused
- I don't know if it is relevant, but this bug occurs with both test ads and real ads (in a launched product) 
- the example project uses a bare-bones implementation of AdMob, using [the sample code from this repository](https://github.com/googleads/googleads-mobile-unity/blob/master/samples/HelloWorld/Assets/Scripts/GoogleAdMobController.cs) and [the official guide](https://developers.google.com/admob/unity/interstitial)
- I haven't tested it, but I think this issue happens with reward ads as well (`OnAdClosed` and maybe even `OnUserEarnedReward` with proper timing)
- the issue doesn't seem to occur on Android devices by opening the notifications pull-down menu, might be because that doesn't pause the game or the ad

**Comment by irakli** [comment]
Events aren't invoked from the main thread, so it's not guaranteed that you'll receive any callbacks.

Wrap your callbacks methods with and it should work.

 
```
MobileAdsEventExecutor.ExecuteInUpdate(() =>
{
    Debug.Log($"Rewarded user");

    // Your code
});
```

**Comment by PokerDawg** [comment]
Hello @irakli

Changing the `AdMobManager.OnInterstitialAdClosed` method from:
```
void OnInterstitialAdClosed(object sender, System.EventArgs args)
{
    LogMessage("Interstitial ad closed");
    RequestAndLoadInterstitialAd();
}
```
... to:
```
void OnInterstitialAdClosed(object sender, System.EventArgs args)
{
    MobileAdsEventExecutor.ExecuteInUpdate(() =>
    {
        LogMessage("Interstitial ad closed");
        RequestAndLoadInterstitialAd();
    });
}
```
... does not solve the issue. I can still reproduce the bug every single time I open the control center immediately after closing the ad.

**Comment by NVentimiglia** [comment]
@PokerDawg I implemented the suggested fix of wrapping the callback handler within `ExecuteInUpdate()`. The result looked correct to me (image below). I will be closing this issue, please feel free to reopen if there is something I missed or you are still stuck.

![image](https://user-images.githubusercontent.com/125889/147281772-7c17fde5-de1e-46b0-871e-a1a20fe988de.png)
![image](https://user-images.githubusercontent.com/125889/147281799-df53cc4a-4a11-4781-be40-3f764b1b9ce6.png)

**Comment by PokerDawg** [comment]
Hello @NVentimiglia 

I have wrapped the ```AdMobManager.LogMessage``` method's contents in ```ExecuteInUpdate()```, like your screenshot, and I am still getting the same result.
Have you managed to reproduce the problem without ```ExecuteInUpdate()```?

As an aside, if ```AdMobManager.OnInterstitialAdClosed``` looks like this
```
void OnInterstitialAdClosed(object sender, System.EventArgs args)
{
    MobileAdsEventExecutor.ExecuteInUpdate(() =>
    {
        LogMessage("Interstitial ad closed");
        RequestAndLoadInterstitialAd();
    });
}
```
... then does modifying the ```AdMobManager.LogMessage``` method with ```ExecuteInUpdate()``` even do anything? Presumably it's already getting called from an ```Update()``` somewhere, right??

**Comment by PokerDawg** [comment]
@NVentimiglia 
This problem is still not solved.
Can you reopen this? Or, I can create a new issue.

**Comment by dethroneofall** [comment]
> @PokerDawg I implemented the suggested fix of wrapping the callback handler within `ExecuteInUpdate()`. The result looked correct to me (image below). I will be closing this issue, please feel free to reopen if there is something I missed or you are still stuck.
> 
> ![image](https://user-images.githubusercontent.com/125889/147281772-7c17fde5-de1e-46b0-871e-a1a20fe988de.png) ![image](https://user-images.githubusercontent.com/125889/147281799-df53cc4a-4a11-4781-be40-3f764b1b9ce6.png)

This problem is still not solved.
