### ISSUE TITLE
Reward ads is zoom in in my android

### ISSUE THREAD

**Issue by anhnhgtv** [googleads/googleads-mobile-unity#1951]
My environment
  * Unity version: 2020.3.13f1
  * Google Mobile Ads Unity plugin version: 7.0.0
  * Platform: Android
  * Platform OS version: Android 12
  * Any specific devices issue occurs on: Samsung galaxy S10 plus
  * Mediation ad networks used, and their versions: NO

My Video reward ads are zoomin and not fully visible on my device. On my iphone it still works fine.

Screenshot:

![Screenshot_20220305-234552_Co The GTV](https://user-images.githubusercontent.com/86297228/156892964-aa3d70c2-df46-4627-aa43-beb37545bee0.jpg)
![Screenshot_20220305-234532_Co The GTV](https://user-images.githubusercontent.com/86297228/156892967-ee18f50b-3b28-4f81-8e4e-4526cf0397f0.jpg)

**Comment by anhnhgtv** [comment]
Please fix

**Comment by PokerDawg** [comment]
We also have this issue. 
I think I narrowed it down a bit:
- it's happening in the newest version (7.0.0), but we also have a game that hasn't been updated in almost 3 years (so an older version), and the problem occurs there as well
- it's happening with admob ads, but also with unity ads (we're using UnityAds mediation with the AdMob plugin); you can see this in the attached picture, the Unity privacy icon is visible in the corner
![unity ad 2](https://user-images.githubusercontent.com/11318436/159901548-68efeecc-a3d1-48bb-9eba-ac312fba687e.png)
- besides fullscreen ads (interstitials and rewards), it also happens in banner ads, and you can swipe across them to scroll the ad around inside the view (if that makes sense)
![test banner](https://user-images.githubusercontent.com/11318436/159901544-04d6f393-ee41-406e-a2be-d13f9f9cb44c.JPEG)
- we have managed to narrow it down to only a few devices, all of them Samsung phones: A52, S10+ and S21; all of these phones are running on android 12, and are using One UI version 4.0, or 4.1; the problem does not seem to occur on any of our other devices
- an interesting point, on the Samsung S10+ and S21, the problem only occurs if the phone has it's resolution set to "WQHD+" (the highest it can go); if the resolution is set to lower values, the ads look normal
@anhnhgtv you mentioned you are using an S10+, check if reducing the resolution does anything.
![resolution](https://user-images.githubusercontent.com/11318436/159903173-5310062f-6677-4e9a-8958-8f972af87567.png)

Overall, this seems like a scaling issue, maybe the phone reports an incorrect scale or resolution to the ad, and it's displayed all wrong. Besides the way the ads look, there doesn't seem to be anything wrong, as in warnings or errors.


Pictures:
![interstitial landscape](https://user-images.githubusercontent.com/11318436/159901534-2cf84ff2-2e03-49d5-a7da-7a1f6c2f1e1f.JPEG)
![real interstitial](https://user-images.githubusercontent.com/11318436/159901540-4992c46e-2c3a-432d-92c6-0b2d28616746.JPEG)
![test interstitial](https://user-images.githubusercontent.com/11318436/159901546-52e73732-8b93-46b4-b2b3-fe205dd4f847.JPEG)

**Comment by anhnhgtv** [comment]
@PokerDawg Thank you for the useful information.  It is true that the ad seems to be broken on samsung devices, using OneUI version 4.x and Android 12. 
And interestingly when I changed the screen resolution from WQHD+ to FHD+ on my Samsung s10+, the ad worked  perfectly.

![Screenshot_20220324-194938_Settings](https://user-images.githubusercontent.com/86297228/159921622-86640f63-9a66-4022-824a-86e9c13482ed.jpg)
![Screenshot_20220324-194927_Tuong Ky](https://user-images.githubusercontent.com/86297228/159921641-db9cc0fc-390f-404b-93ca-0bcf8cdcf530.jpg)

Because Samsung devices using OneUI are quite common.  I hope the Admob Unity Sdk Dev Team can fix the problem in the next update.

Thank everyone.

**Comment by kungshinhean** [comment]
Confirmed happened on our game too, tested on note 10 plus with android 12, admob 7.0

**Comment by Ecapyc** [comment]
I'm using Galaxy S20. There was no problem with android 11.
But after update the OS to android 12, all admob ads are showing like above.
Not only my app, but also any other app downloaded at Play store.

**Comment by berkceb** [comment]
I came across this bug as well in Samsung A52 device running on Android 12. I also tested it in Samsung S20 running on Android 11 and everything is fine.

**Comment by PretzelSummoner** [comment]
I have an S20FE and this issue just start today with me. I also have an S8 and A70 that work fine. No zoomed ads. Is this an issue that we (the devs of the game) can fix or do we need for an update to fix this issue.

**Comment by matthunt1984** [comment]
Just another Samsung user on A52, Android 12 One UI 4.1
Had this problem for a few weeks on different apps. Not sure on root cause but would appreciate a fix.
The ads are damaged and the ones that have the close button off screen is a real pain.
I've noticed sometimes the cross is off screen but is behind the gameboost menu bar. Clicking the add and the backing out again can make it visible.

Will try changing screen resolution in meantime.

**Comment by coollad10** [comment]
Facing the same issue on Samsung F62, no option to change resolution on my model. Stuck with this irritating issue. Please update with a fix!

**Comment by matthunt1984** [comment]
A52 does not allow screen resolution change and this issue can be really annoying when the close button is not shown. I'm not an Ads/Android dev but have some more screenshots to share [here](https://imgur.com/a/5YD8kZ1)

I have contact Samsung customer support too with little success so far, but I had some potential (or random) success with force stopping the apps which ended that live chat session.

I have since noticed that my screenshots of the problem all include the menu bar at the bottom. Sometimes the add shows at the bottom and the ads 'seem' ok, but I haven't seen an ad problem where the bar wasn't showing.

Some of the ads that are working fine don't have the bar, and when i tap  (or take a screenshot) I can see the bar appears (sometimes obscuring close button) and will then retract again fine.

I might just be throwing out red herrings here, but looking for support wherever I can get it and trying both the Ads software and Samsung angles!

**Comment by camozera** [comment]
Same issue on Galaxy A52s
![Screenshot_20220511-203933_Oxide - Survival Island](https://user-images.githubusercontent.com/105399074/167966984-96ae1829-eba9-428e-b15e-dce9feccab7a.jpg)

**Comment by hass101** [comment]
I would just like to add that the offscreen problem for interstitial ads is happening not only with the latest release but also older releases. I have only just found this out because my old test device was a pixel and it was not happening on that. My new test device is a samsung galaxy a52s and that is why I have found this bug, as it seems to be a problem with samsung devices specifically, as everyone else is mentioning. This is obviously a problem due to the popularity of these devices.

**Comment by fzs1994** [comment]
Same issue on my S20 FE

**Comment by GusterF** [comment]
Same issue on Samsung A71. Also, occasionally there is a 'feedback' button over the top of the 'x' which prevents closing the ad.

**Comment by YongjinK** [comment]
My app also has this issue. There are some more info to share here.

1. This issue happens only with admob unity plugin. The native android plugin displays ads correctly. So this is not the problem of android 12/oneui. Admob unity plugin should fix its problem.
2. The real problem is not the zoom. In wqhd mode, reward and interstial ads loader does not load fhd ads. So lower ecpm ads and even 5 secs ads are loaded. This highly impacts the overall ecpm of our app. The admob unity team needs to seriously face on this issue and solve it asap.
3. changing the unity app's Screen.currentresolution does not solve the issue. the value can be changed by dpi setting in android player build setting. But with 1080x2XXX current resolution, the problem still occurs. It seems the plugin refers to Screen.resolutions or Screen.GetResolutions to decide ads to load. I guess if the highest resolution from those info is higher than fhd, it skips fhd video ads and tries to load wqhd video ads.

**Comment by YongjinK** [comment]
I tested this issue with 7.0.1 and 7.0.2 and the problem still happens with those newer versions.

**Comment by wwawrzy** [comment]
The same issue in my app :(

**Comment by celp** [comment]
The same issue in my app (on Galaxy A52). It is a critical issue. Please fix.

**Comment by PokerDawg** [comment]
An update on this issue:

Our Samsung A52 received an update a day ago; after it, the ads seem to look normal again.
![1655271531080](https://user-images.githubusercontent.com/11318436/174001062-df7d6a5f-0ac8-437f-8a54-5c8e16fde717.JPEG)

https://doc.samsungmobile.com/SM-A526B/ROM/doc.html
In their update database, there's no mention of any issues or fixes related to ads. Our problems started to occur around February, so I assume the "One UI 4 Upgrade (Android 12)" update broke things. 

https://us.community.samsung.com/t5/Android-12/Ads-in-apps-stretched-out-as-well-as-some-webpages/m-p/2198021
We found this forum thread with users having, what seems to be, this exact problem, even with deformed ads in the browser.

@ all the people that posted here: be on the lookout for a Samsung update on your phones, and maybe report back if that fixed anything for you.

**Comment by jeffyuio1129** [comment]
It seems to be a problem with the Samsung GOS app.

Anything that is not in the GOS app DB runs normally.

**Comment by RamonNeres** [comment]
> An update on this issue:
> 
> Our Samsung A52 received an update a day ago; after it, the ads seem to look normal again. ![1655271531080](https://user-images.githubusercontent.com/11318436/174001062-df7d6a5f-0ac8-437f-8a54-5c8e16fde717.JPEG)
> 
> https://doc.samsungmobile.com/SM-A526B/ROM/doc.html In their update database, there's no mention of any issues or fixes related to ads. Our problems started to occur around February, so I assume the "One UI 4 Upgrade (Android 12)" update broke things.
> 
> https://us.community.samsung.com/t5/Android-12/Ads-in-apps-stretched-out-as-well-as-some-webpages/m-p/2198021 We found this forum thread with users having, what seems to be, this exact problem, even with deformed ads in the browser.
> 
> @ all the people that posted here: be on the lookout for a Samsung update on your phones, and maybe report back if that fixed anything for you.

updated my S20 FE and the problem continues

**Comment by jessymilare** [comment]
Same problem with my Samsung M52 5G, everything updated.

**Comment by anhnhgtv** [comment]
Still problem. Please fix :(

**Comment by soranoo** [comment]
Same issue on Samsung Note 10 Lite (Android12)

**Comment by strombinho** [comment]
Same issue here, S20 FE. I've contacted Samsung but they say it's not their problem and I should contact the responsible for the app. Since this is not exactly an app issue, who should we try to contact?

They gave the same answer for this other user here:

https://eu.community.samsung.com/t5/galaxy-a-series/faulty-display-of-in-app-ads/td-p/5308882

**Comment by PokerDawg** [comment]
@strombinho Nothing new there, trying to throw the blame over to someone else. 
For what it’s worth, that Samsung update did seem to fix our problem, without any other changes from our end. Unfortunately, it seems that it doesn’t fix it for anyone else, or maybe other phones, or regions, did not receive this specific update, I don’t know. 
This whole thing is such a mess…

**Comment by moldovev** [comment]
I have just updated to the latest A52 (what @RamonNeres posted) version and the problem is fixed for my phone.

**Comment by AwsomeCode** [comment]
This issue is also happening in iPhone as well. 
Checked on iphone 12.
Ads library is broken for sure.

**Comment by SG2010** [comment]
My wife has Samsung A12 which seems fine but I have Samsung A71 still have the issue.

**Comment by umairh2018** [comment]
Getting the same issues on Samsung Tab 6 Lite after updating to Android 12. This issue happens when your game is optimized by the Samsung Game Optimize Service app. On stopping this GOS, issue is resolved. But how can we ask our user to do so is an issue.

**Comment by umairh2018** [comment]
After Updating the Samsung One UI version to 4.1.1 (update received on Monday 17 October 2022), the issue got fixed in Android 12 versions.

**Comment by assafcohen1** [comment]
Can anyone from Admob please comment on this? 
Is it an issue with Admob, Samsung, or maybe we implemented the SDK incorrectly?

**Comment by kunny** [comment]
Since there were no recent activities for this issue, we are therefore reluctantly going to close this bug for now.

If you are still experiencing the problem, please file a new issue with the same description, what happens and system / network tracing / Charles logs.

All system setups can be slightly different, so it's always better to open new issues and reference the related ones. Thanks for your contribution.
