### ISSUE TITLE
HelloWorld Sample- Native Overlay crash

### ISSUE THREAD

**Issue by idevxgame2024** [googleads/googleads-mobile-unity#3345]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2023.2.17f1
  * Google Mobile Ads Unity plugin version: 9.1
  * Platform: Android (iOS, Android, Unity Editor)
  * Platform OS version: _____ (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: _____

### [REQUIRED] Step 2: Describe the problem
When run Sample , after Native Overlay Ad load success ,  if press "Render" it will show ad on top screen, if press "show ad" , the app crash.

**Comment by NVentimiglia** [comment]
Thank you for reporting this,

- What platform are you testing on (iOS / Android).
- Do you have any crash logs you can share?

**Comment by idevxgame2024** [comment]
Hi,
Im test on Xiaomi Note 12, Android ver 14.
At this time. im so busy, weekend i will re-test anh send crash log to you,
idevXGame

**Comment by NVentimiglia** [comment]
If you have issues please reopen this issue and let me know.

**Comment by naved1197** [comment]
```2024-10-31 16:26:32.478 31725 31725 Error AndroidRuntime FATAL EXCEPTION: main
2024-10-31 16:26:32.478 31725 31725 Error AndroidRuntime Process: com.Cubehole.HelloWorld, PID: 31725
2024-10-31 16:26:32.478 31725 31725 Error AndroidRuntime java.lang.NoSuchFieldError: No static field icon of type I in class Lcom/google/unity/ads/R$id; or its superclasses (declaration of 'com.google.unity.ads.R$id' appears in /data/app/~~ap5ongd4hu85-QNbMduiWg==/com.Cubehole.HelloWorld-Fa_QDIXE3LRgziJaTK3KFg==/base.apk!classes2.dex)
2024-10-31 16:26:32.478 31725 31725 Error AndroidRuntime 	at com.google.android.ads.nativetemplates.TemplateView.onFinishInflate(TemplateView.java:290)
2024-10-31 16:26:32.478 31725 31725 Error AndroidRuntime 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1159)
2024-10-31 16:26:32.478 31725 31725 Error AndroidRuntime 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1107)
2024-10-31 16:26:32.478 31725 31725 Error AndroidRuntime 	at android.view.LayoutInflater.inflate(LayoutInflater.java:703)
2024-10-31 16:26:32.478 31725 31725 Error AndroidRuntime 	at android.view.LayoutInflater.inflate(LayoutInflater.java:544)
2024-10-31 16:26:32.478 31725 31725 Error AndroidRuntime 	at android.view.LayoutInflater.inflate(LayoutInflater.java:491)
2024-10-31 16:26:32.478 31725 31725 Error AndroidRuntime 	at com.google.unity.ads.nativead.UnityNativeTemplateStyle.asTemplateView(UnityNativeTemplateStyle.java:58)
2024-10-31 16:26:32.478 31725 31725 Error AndroidRuntime 	at com.google.unity.ads.nativead.UnityNativeTemplateAd$5.run(UnityNativeTemplateAd.java:264)
2024-10-31 16:26:32.478 31725 31725 Error AndroidRuntime 	at android.os.Handler.handleCallback(Handler.java:958)
2024-10-31 16:26:32.478 31725 31725 Error AndroidRuntime 	at android.os.Handler.dispatchMessage(Handler.java:99)
2024-10-31 16:26:32.478 31725 31725 Error AndroidRuntime 	at android.os.Looper.loopOnce(Looper.java:257)
2024-10-31 16:26:32.478 31725 31725 Error AndroidRuntime 	at android.os.Looper.loop(Looper.java:368)
2024-10-31 16:26:32.478 31725 31725 Error AndroidRuntime 	at android.app.ActivityThread.main(ActivityThread.java:8839)
2024-10-31 16:26:32.478 31725 31725 Error AndroidRuntime 	at java.lang.reflect.Method.invoke(Native Method)
2024-10-31 16:26:32.478 31725 31725 Error AndroidRuntime 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
2024-10-31 16:26:32.478 31725 31725 Error AndroidRuntime 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
```

I have the same issue ad loads fine but when I press the Load or Render Ad button in the sample app the app crashes

**Comment by nmtoan91** [comment]
I have a same problem, please help @NVentimiglia

**Comment by NVentimiglia** [comment]
@nmtoan91 Can you create a new bug

**Comment by aperhaite** [comment]
I'm having the same issue. I'm testing it on a real device: Samsung Galaxy S21 Ultra 5G SM-G998B/DS
- GoogleMobileAds-v9.5.0.unitypackage
- I'm testing with my real ad id, not a test id
- Unity 6000.0.32f1

**Comment by NVentimiglia** [comment]
Thanks, we are looking into the issue.

**Comment by aperhaite** [comment]
@NVentimiglia  do you have an ETA for the fix? It's currently blocking my Native Overlay ads integration in my production project. Thanks!

**Comment by varelaj** [comment]
In Unity 2022 works fine, the problem is Unity 6.

**Comment by harhar111** [comment]
I have the same issue.
Even with the latest GoogleMobileAds-v9.6.0.unitypackage the issue is there.
Again, in Unity 2022 works fine, the crash happens only in Unity 6.

**Comment by viveksaini75** [comment]
Hi @NVentimiglia, any update for Unity 6 about this issue

**Comment by melkayal** [comment]
Any updates about the issue on Unity 6

**Comment by avadh29** [comment]
![Image](https://github.com/user-attachments/assets/c03b27c5-81e1-46a0-8d7d-0de0981fefde)

crash happen on Native overlay ads when try to call render Ads

**Comment by JosueR2** [comment]
The same here with unity 6 and google ads 9.6
native overlay

java.lang.Error: FATAL EXCEPTION [main]
Unity version   : 6000.0.41f1

Caused by: java.lang.NoSuchFieldError: No static
field icon of type I in class Lcom/google/unity/
ads/R$id; or its superclasses 

at com.google.android.ads.nativetemplates.TemplateView.onFinishInflate(TemplateView.java:291)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:a:1170)
at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1113)
at android.view.LayoutInflater.inflate(LayoutInflater.java:711)
at android.view.LayoutInflater.inflate(LayoutInflater.java:a:1170)
at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1113)
at android.view.LayoutInflater.inflate(LayoutInflater.java:711)
at android.view.LayoutInflater.inflate(LayoutInflater.java:548)
at android.view.LayoutInflater.inflate(LayoutInflater.java:486)
at com.google.unity.ads.nativead.UnityNativeTemplateStyle.asTemplateView(UnityNativeTemplateStyle.java:58)
at com.google.unity.ads.nativead.UnityNativeTemplateAd$5.run(UnityNativeTemplateAd.java:264)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:211)
at android.os.Looper.loop(Looper.java:300)
at android.app.ActivityThread.main(ActivityThread.java:8503)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

**Comment by vinkini** [comment]
This should be addressed in the latest release. Please try with the 10.1.0 release.

**Comment by ducyb294** [comment]
> This should be addressed in the latest release. Please try with the 10.1.0 release.

I tried and it keeps crashing.

**Comment by aperhaite** [comment]
@vinkini Still failing. 

It's so sad that after many years of using admob, now I have to switch to another Ad provider that supports native ads

**Comment by vinkini** [comment]
Hi @ducyb294, @aperhaite ,

I am unable to reproduce in my environment. Are you trying with the HelloWorld sample app? Which Unity Editor Version and Android version are you using?

**Comment by nadiaparveenLegacy** [comment]
@aperhaite @ducyb294 , @vinkini Did u find any solution? I used AdMob SDK version 9.5.0 then i used version 10.1.0 in my project but still same issue with both versions on Unity 6. I am using Unity 6000.0.27f1. Its showing exception before Native Overlay Ad load success and when I try to show Native Overlay Ad, my game crashes.

**Comment by NVentimiglia** [comment]
Closing. This issue is a year olf and should be fixed in a newer version of the SDK.
