### ISSUE TITLE
Update googleads 9.1.0 iOS GADMediationAdapterFacebook not ready.

### ISSUE THREAD

**Issue by YianChen75** [googleads/googleads-mobile-unity#3355]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: 2022.3.27f1
  * Google Mobile Ads Unity plugin version: 9.1.0
  * Plugin installation method: unitypackage
  * Platform: iOS (iOS, Android, Unity Editor)
  * Platform OS version: 17
  * Any specific devices issue occurs on: _____
  * Mediation ad networks used, and their versions: _____

#### Steps to reproduce:

What happened? How can we make the problem occur?

Update to:
AdMob SDK 9.1.0
Mediation:
GoogleMobileAdsMediationFacebook 6.15.0

Encountering the issue "Adapter: GADMediationAdapterFacebook not ready." on iOS.
Could you please assist in resolving this?

in debugging message
Failed: Adapter failed to initialize. Adapter raised an exception during setup. Adapter: GADMediationAdapterFacebook, Exception: FBAdInitSettings is a final class and cannot be subclassed. FBAdInitSettings

Please share a downloadable sample project that reproduces the bug, if
available. This greatly helps us to diagnose and fix the issue faster.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
public void MobileAdsInit()
{
    MobileAds.Initialize((initStatus) =>
            {
                Dictionary<string, AdapterStatus> map = initStatus.getAdapterStatusMap();
                foreach (KeyValuePair<string, AdapterStatus> keyValuePair in map)
                {
                    string className = keyValuePair.Key;
                    AdapterStatus status = keyValuePair.Value;
                    switch (status.InitializationState)
                    {
                        case AdapterState.NotReady:
                            {
                                // The adapter initialization did not complete.
                                Debug.LogErrorFormat("[Log] AdMobProxy Adapter: {0} not ready.", className);
    
                            }
                            break;
                        case AdapterState.Ready:
                            {
                                // The adapter was successfully initialized.
                                Debug.LogFormat("[Log] AdMobProxy Adapter: {0} is initialized.", className);
                            }
                            break;
                        default:
                            break;
                    }
                }
    
            });
}
```

**Comment by NVentimiglia** [comment]
@YianChen75 

Thank you, I verified that this is an issue and we are looking into fixing this.

**Comment by NVentimiglia** [comment]
This should be fixed. Please update and try again. If you have issues please reopen this issue and let me know.

**Comment by artemtarassov** [comment]
> This should be fixed. Please update and try again. If you have issues please reopen this issue and let me know.

@NVentimiglia 
the problem still persists. i get:

> Exception: FBAdInitSettings is a final class and cannot be subclassed.

here is my pod: 

source 'https://github.com/CocoaPods/Specs'

platform :ios, '14.0'

target 'UnityFramework' do
  pod 'FBAudienceNetwork', '~> 6.15'
  pod 'FBSDKCoreKit', '~> 17.0.1'
  pod 'FBSDKCoreKit_Basics', '~> 17.0.1'
  pod 'FBSDKGamingServicesKit', '~> 17.0.1'
  pod 'FBSDKLoginKit', '~> 17.0.1'
  pod 'FBSDKShareKit', '~> 17.0.1'
  pod 'GoogleMobileAdsMediationFacebook', '6.15.1.0'
  pod 'GoogleMobileAdsMediationFyber', '8.3.0.0'
  pod 'GoogleMobileAdsMediationUnity', '4.12.0.0'
  pod 'GoogleMobileAdsMediationVungle', '7.3.2.0'
  pod 'Google-Mobile-Ads-SDK', '~> 11.6.0'
end
target 'Unity-iPhone' do
end
use_frameworks!
