### ISSUE TITLE
App crashes on Admob integration in Unity 6.0 and Ads work on Unity editor but not on android device

### ISSUE THREAD

**Issue by LeeAns** [googleads/googleads-mobile-unity#3761]
### [REQUIRED] Step 1: Describe your environment

  * Unity version: Unity 6000.0.43f1
  * Google Mobile Ads Unity plugin version: 10.0 (I also tried the older ones) 
  * Plugin installation method: Import (Unity package manager, .unitypackage import)
  * Platform: Android (iOS, Android, Unity Editor)
  * Platform OS version: Android target sdk 34 (eg iOS 10, Android 9)
  * Any specific devices issue occurs on: All of the android devices
  * Mediation ad networks used, and their versions: not using any

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

...................
the problem is after integrating admob in unity project and following your online documentation, ads work in unity editor but not in the mobile app and the android mobile crashes on opening after installing in a android device. 

your documentation on gradle update to use latest admob plugin in older unity versions is outdated and missies steps and has the same issue.
.....................

Please share a downloadable sample project that reproduces the bug, if
available. This greatly helps us to diagnose and fix the issue faster.

Import it yourself and see it , my app got suspended on google playsotre because of your bug
i have been stuck on it for more than a year

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by NVentimiglia** [comment]
What is the error you are seeing ?

**Comment by LeeAns** [comment]
there is no error on pc

but on mobile the app crashes, no error pops up on mobile

**Comment by avadh29** [comment]
im using admob 10.0.0
i have crash issue in unity 6.0.32
when click load native overlay workes with when click on render ad its crash the game :
0001-01-01 00:00:00.000 -1 -1 Info  --------- beginning of crash
2025-04-07 09:26:33.643 15069 15069 Error AndroidRuntime FATAL EXCEPTION: main
2025-04-07 09:26:33.643 15069 15069 Error AndroidRuntime Process: com.DefaultCompany.HelloWorld, PID: 15069
2025-04-07 09:26:33.643 15069 15069 Error AndroidRuntime java.lang.NoSuchFieldError: No static field icon of type I in class Lcom/google/unity/ads/R$id; or its superclasses (declaration of 'com.google.unity.ads.R$id' appears in base.apk!classes3.dex)
2025-04-07 09:26:33.643 15069 15069 Error AndroidRuntime 	at com.google.android.ads.nativetemplates.TemplateView.onFinishInflate(TemplateView.java:291)
2025-04-07 09:26:33.643 15069 15069 Error AndroidRuntime 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1190)
2025-04-07 09:26:33.643 15069 15069 Error AndroidRuntime 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1138)
2025-04-07 09:26:33.643 15069 15069 Error AndroidRuntime 	at android.view.LayoutInflater.inflate(LayoutInflater.java:695)
2025-04-07 09:26:33.643 15069 15069 Error AndroidRuntime 	at android.view.LayoutInflater.inflate(LayoutInflater.java:547)
2025-04-07 09:26:33.643 15069 15069 Error AndroidRuntime 	at android.view.LayoutInflater.inflate(LayoutInflater.java:494)
2025-04-07 09:26:33.643 15069 15069 Error AndroidRuntime 	at com.google.unity.ads.nativead.UnityNativeTemplateStyle.asTemplateView(UnityNativeTemplateStyle.java:58)
2025-04-07 09:26:33.643 15069 15069 Error AndroidRuntime 	at com.google.unity.ads.nativead.UnityNativeTemplateAd$5.run(UnityNativeTemplateAd.java:264)
2025-04-07 09:26:33.643 15069 15069 Error AndroidRuntime 	at android.os.Handler.handleCallback(Handler.java:938)
2025-04-07 09:26:33.643 15069 15069 Error AndroidRuntime 	at android.os.Handler.dispatchMessage(Handler.java:99)
2025-04-07 09:26:33.643 15069 15069 Error AndroidRuntime 	at android.os.Looper.loop(Looper.java:257)
2025-04-07 09:26:33.643 15069 15069 Error AndroidRuntime 	at android.app.ActivityThread.main(ActivityThread.java:8192)
2025-04-07 09:26:33.643 15069 15069 Error AndroidRuntime 	at java.lang.reflect.Method.invoke(Native Method)
2025-04-07 09:26:33.643 15069 15069 Error AndroidRuntime 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
2025-04-07 09:26:33.643 15069 15069 Error AndroidRuntime 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)

**Comment by avadh29** [comment]
im using admob 10.0.0
i have crash issue in unity 6.0.32
Also Try in sample HelloWorld but same crash happen
when click load native overlay works But after load when click on render ad its crash the game :
0001-01-01 00:00:00.000 -1 -1 Info  --------- beginning of crash
2025-04-07 09:26:33.643 15069 15069 Error AndroidRuntime FATAL EXCEPTION: main
2025-04-07 09:26:33.643 15069 15069 Error AndroidRuntime Process: com.DefaultCompany.HelloWorld, PID: 15069
2025-04-07 09:26:33.643 15069 15069 Error AndroidRuntime java.lang.NoSuchFieldError: No static field icon of type I in class Lcom/google/unity/ads/R$id; or its superclasses (declaration of 'com.google.unity.ads.R$id' appears in base.apk!classes3.dex)
2025-04-07 09:26:33.643 15069 15069 Error AndroidRuntime 	at com.google.android.ads.nativetemplates.TemplateView.onFinishInflate(TemplateView.java:291)
2025-04-07 09:26:33.643 15069 15069 Error AndroidRuntime 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1190)
2025-04-07 09:26:33.643 15069 15069 Error AndroidRuntime 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1138)
2025-04-07 09:26:33.643 15069 15069 Error AndroidRuntime 	at android.view.LayoutInflater.inflate(LayoutInflater.java:695)
2025-04-07 09:26:33.643 15069 15069 Error AndroidRuntime 	at android.view.LayoutInflater.inflate(LayoutInflater.java:547)
2025-04-07 09:26:33.643 15069 15069 Error AndroidRuntime 	at android.view.LayoutInflater.inflate(LayoutInflater.java:494)
2025-04-07 09:26:33.643 15069 15069 Error AndroidRuntime 	at com.google.unity.ads.nativead.UnityNativeTemplateStyle.asTemplateView(UnityNativeTemplateStyle.java:58)
2025-04-07 09:26:33.643 15069 15069 Error AndroidRuntime 	at com.google.unity.ads.nativead.UnityNativeTemplateAd$5.run(UnityNativeTemplateAd.java:264)
2025-04-07 09:26:33.643 15069 15069 Error AndroidRuntime 	at android.os.Handler.handleCallback(Handler.java:938)
2025-04-07 09:26:33.643 15069 15069 Error AndroidRuntime 	at android.os.Handler.dispatchMessage(Handler.java:99)
2025-04-07 09:26:33.643 15069 15069 Error AndroidRuntime 	at android.os.Looper.loop(Looper.java:257)
2025-04-07 09:26:33.643 15069 15069 Error AndroidRuntime 	at android.app.ActivityThread.main(ActivityThread.java:8192)
2025-04-07 09:26:33.643 15069 15069 Error AndroidRuntime 	at java.lang.reflect.Method.invoke(Native Method)
2025-04-07 09:26:33.643 15069 15069 Error AndroidRuntime 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
2025-04-07 09:26:33.643 15069 15069 Error AndroidRuntime 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)

Please update fast and solve this native overlay ads issue with unity 6

**Comment by vinkini** [comment]
Hello, we ran this with Unity 6 (6000.0.40f1) and we are able to reproduce this. This is not seen in 2023 and versions below so if its possible for you to use a different editor while we investigate further, please do so.

**Comment by LeeAns** [comment]
> Hello, we ran this with Unity 6 (6000.0.40f1) and we are able to reproduce this. This is not seen in 2023 and versions below so if its possible for you to use a different editor while we investigate further, please do so.

The issue also exists in previous versions. I have tested it with Unity 6000.0.43f1, Unity 2022.3.22f1, and Unity 2021.3.8f1.

The only reason I switched to Unity 6 was because the earlier versions were giving Gradle errors when using your AdMob plugin.

I tried solving the Gradle issues by following your documentation, but I wasn’t successful — the Gradle update documentation appears to be incomplete and outdated.

**Comment by Sadeed521** [comment]
Hello everyone, I'm having the same issue on version 2022.3.43f1. I tried different android devices but it didn't worked.

**Comment by SeriouslyRichMan** [comment]
Same problem, Unity 6 (6000.0.43f1), admob 10.0.0

**Comment by vinkini** [comment]
This should be addressed in the latest release. Please try with v10.1.0 and let us know if it works for you.

**Comment by kahluasoft** [comment]
Problem in 6000.0.46f1 & v10.0.0, but Work fine in v10.1.0.
Thank you very much.

**Comment by SeriouslyRichMan** [comment]
The app still crashes on the device, Unity 6 (6000.0.43f1), admob 10.1.0.

**Comment by vinkini** [comment]
Hey @SeriouslyRichMan,
I tested with the HelloWorld sample app provided [here](https://github.com/googleads/googleads-mobile-unity/tree/main/samples/HelloWorld) with 10.1.0 on Unity 6000.0.40f1 and was able to see the native overlay load and render on a medium template ad on the bottom of the app. Can you try with the sample above and see if it still crashes for you?

**Comment by SeriouslyRichMan** [comment]
Let me add. I discovered that the game was crashing on the device when calling the method SetActive(true) on a gameObject. I had to put in some effort to detect it, since I didn't expect the issue to manifest in such a seemingly harmless place. I managed to work around it in a somewhat hacky way — by adding a delay of 1 second before calling SetActive(true). Could you please explain this behavior? I didn't observe this in older versions of AdMob, and the bug doesn't occur in the Unity editor itself.

**Comment by vinkini** [comment]
Glad to hear you managed to get it working! We are grateful for all the feedback we receive and are actively working on improving your experience with the plugin.
I am definitely concerned about having to add delays to prevent crashes and would love to understand more about your use case. What is the gameObject used for?  Is it to position the ad during render? Is the crash log the same as the one seen above? We would love to replicate this and add a fix on our end if possible.

**Comment by SeriouslyRichMan** [comment]
I copied a part of the errors from the log:

2025.05.05 00:12:40.020 11856 15468 Error CRASH *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
2025.05.05 00:12:40.020 11856 15468 Error CRASH Version '6000.0.43f1 (97272b72f107)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'arm64-v8a', Stripping 'Enabled'
2025.05.05 00:12:40.021 11856 15468 Error CRASH Build fingerprint: 'Xiaomi/aristotle_ru/aristotle:15/AP3A.240905.015.A2/OS2.0.2.0.VMFRUXM:user/release-keys'
2025.05.05 00:12:40.021 11856 15468 Error CRASH Revision: '0'
2025.05.05 00:12:40.021 11856 15468 Error CRASH ABI: 'arm64'
2025.05.05 00:12:40.021 11856 15468 Error CRASH Timestamp: 2025-05-05 00:12:40.021106208+0300
2025.05.05 00:12:40.021 11856 15468 Error CRASH pid: 11856, tid: 15468, name: Thread-35  >>> com.CompanyName.GameName <<<
2025.05.05 00:12:40.021 11856 15468 Error CRASH uid: 10549
2025.05.05 00:12:40.021 11856 15468 Error CRASH signal 5 (SIGTRAP), code -6 (SI_TKILL), fault addr --------
2025.05.05 00:12:40.021 11856 15468 Error CRASH     x0  0000000000000000  x1  0000000000003c6c  x2  0000000000000005  x3  0000000000000000
2025.05.05 00:12:40.021 11856 15468 Error CRASH     x4  37353334301f1f35  x5  37353334301f1f35  x6  37353334301f1f35  x7  7f7f7f7f7f7f7f7f
2025.05.05 00:12:40.021 11856 15468 Error CRASH     x8  0000000000000083  x9  b06188abda8bafb5  x10 0000000000000001  x11 0000000000000000
2025.05.05 00:12:40.021 11856 15468 Error CRASH     x12 0000006f8f62879f  x13 000000723b5152a0  x14 0000000000000001  x15 0000000000000190
2025.05.05 00:12:40.021 11856 15468 Error CRASH     x16 000000725b3d2660  x17 000000725b3bc440  x18 0000006d26c28000  x19 0000006f8f62b740
2025.05.05 00:12:40.021 11856 15468 Error CRASH     x20 00000000000000b3  x21 0000006e79c01a7c  x22 0000006f8f62da80  x23 0000006e7a867334
2025.05.05 00:12:40.021 11856 15468 Error CRASH     x24 0000006f8f62da80  x25 0000006e338dda70  x26 0000000000000043  x27 0000000000000002
2025.05.05 00:12:40.021 11856 15468 Error CRASH     x28 0000000000000000  x29 0000006f8f62bc30
2025.05.05 00:12:40.021 11856 15468 Error CRASH     lr  0000006e7a866f78  sp  0000006f8f62b690  pc  000000725b3bc448  pst 0000000000001000
2025.05.05 00:12:40.021 11856 15468 Error CRASH backtrace:
2025.05.05 00:12:40.021 11856 15468 Error CRASH       #00 pc 00000000000c9448  /apex/com.android.runtime/lib64/bionic/libc.so (tgkill+8) (BuildId: bc5c61ed852b3f4266cdfdd25499ef95)

This is a very strange bug. I will try to explain how this bug manifests. 
In my game, there is a button with an advertisement (image1), which is the parent object for an animated TextMeshProUGUI (image2). I enable the TextMeshProUGUI after the ad is closed (ad.OnAdFullScreenContentClosed += () => { call to the reward method }), so that the player can see the size of the received reward. 
Here is roughly how my code looks:
//---------------------Version with crash
...

ad.OnAdFullScreenContentClosed += () =>
{ 
  GiveReward(); 
}

void GiveReward()
{
  ...
  TextMeshProUGUIAnim.gameObject.SetActive(true) //crash
  ...
}

//---------------------Version without crash
...

ad.OnAdFullScreenContentClosed += () =>
{ 
  GiveReward(); 
}

void GiveReward()
{
  ...
  StartCoroutine(TextMeshProUGUIAnimCoroutine());
  ...
}

IEnumerator TextMeshProUGUIAnimCoroutine()
{
  yield return new WaitForSeconds(1);
  TextMeshProUGUIAnim.gameObject.SetActive(true);//OK
}

![Image](https://github.com/user-attachments/assets/fbb5a3d3-6b55-46cb-af8d-21049387884d)

![Image](https://github.com/user-attachments/assets/6d8e0d14-1cdd-44bd-96ad-af92900c9bd6)

**Comment by SeriouslyRichMan** [comment]
I added MobileAds.RaiseAdEventsOnUnityMainThread = true, but it didn't change the behavior; the app still crashes at the same place. Interestingly, other methods work, such as Play(), but it crashes on SetActive(). Running via a Coroutine is a suitable solution for me, as it doesn't degrade the user experience and resolves the issue. I also want to thank you once again for your attention to my problem and for your excellent support.
