### ISSUE TITLE
banner.Destroy() causes rare crash in production

### ISSUE THREAD

**Issue by rotter** [googleads/googleads-mobile-unity#690]
I'm getting a crash in production in a small subset of cases, less than 1% of players, but still a lot of crashes.

I dont have much info, only the exception/stack trace (below). I can't see any pattern on the crashes regarding Android version (mostly android 5 and 6, but there are some crashes on 7 also) or device/brand (top 3 devices are from different brands).

My code is pretty standard, I dont think it's related to my code as it works on 99%+ of cases, but anyway here it goes:

```
bannerViewAdmob.OnAdFailedToLoad -= HandleOnBannerFailedToLoad;
bannerViewAdmob.OnAdLoaded -= HandleOnBannerLoaded;
bannerViewAdmob.Hide();
bannerViewAdmob.Destroy();  // <----- rare crash here
bannerViewAdmob = null;
```

Exception:
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewTreeObserver com.google.android.gms.ads.AdView.getViewTreeObserver()' on a null object reference

Stack trace:
com.google.unity.ads.Banner.destroy(Banner.java:328)
com.unity3d.player.UnityPlayer.nativeRender(Native Method)
com.unity3d.player.UnityPlayer.c(Unknown Source)
com.unity3d.player.UnityPlayer$e$2.queueIdle(Unknown Source)
android.os.MessageQueue.next(MessageQueue.java:211)
android.os.Looper.loop(Looper.java:122)
com.unity3d.player.UnityPlayer$e.run(Unknown Source)
UnityEngine.AndroidJNISafe.CheckException ()
UnityEngine.AndroidJNISafe.CallVoidMethod (IntPtr obj, IntPtr methodID, UnityEngine.jvalue[] args)
UnityEngine.AndroidJavaObject._Call (System.String methodName, System.Object[] args)
UnityEngine.AndroidJavaObject.Call (System.String methodName, System.Object[] args)
GoogleMobileAds.Android.BannerClient.DestroyBannerView ()
GoogleMobileAds.Api.BannerView.Destroy ()

**Comment by rampara** [comment]
@rotter currently investigating this issue and will follow up when I have more information.

**Comment by rotter** [comment]
I'm also seeing a rare NPE on the same exact line - com.google.unity.ads.Banner.destroy(Banner.java:328).

AndroidJavaException: java.lang.NullPointerException

Managed Stack Trace:
java.lang.NullPointerException
com.google.unity.ads.Banner.destroy(Banner.java:328)
com.unity3d.player.UnityPlayer.nativeRender(Native Method)
com.unity3d.player.UnityPlayer.c(Unknown Source)
...

**Comment by rampara** [comment]
@rotter having trouble reproducing the issue. Will keep it open for now.

**Comment by rotter** [comment]
Thanks for the feedback.

I cant reproduce it as well, and as I mentioned it's pretty rare, happens in less than 1% of the sessions, but it's still a lot. Maybe it happens on an unusual situation such as when the app is being closed, the phone is being shutdown, the disk is completely full, the memory is completely full, etc.

Could you just do a general try/catch on that line? Since it's an exception on the Android side there's nothing I can do, and my app just gets killed when it happens for a silly reason from the point of view of the user (ad-related failure).

Thanks

**Comment by tucano** [comment]
Hello, I have also this issue. Has been fixed in the last version of the plugin?

Thanks

**Comment by rotter** [comment]
I didnt notice this crash for a while, but just noticed them again today. Can you confirm if latest version (from August 31st) should contain the fix? I am running this version and am still facing those crashes:

java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewTreeObserver com.google.android.gms.ads.AdView.getViewTreeObserver()' on a null object reference
com.google.unity.ads.Banner.destroy(Banner.java:365)
com.unity3d.player.UnityPlayer.nativeRender(Native Method)
com.unity3d.player.UnityPlayer.c(Unknown Source)
com.unity3d.player.UnityPlayer$e$2.queueIdle(Unknown Source)
android.os.MessageQueue.next(MessageQueue.java:392)
android.os.Looper.loop(Looper.java:135)
com.unity3d.player.UnityPlayer$e.run(Unknown Source)
UnityEngine.AndroidJNISafe.CheckException () (at <7c518b55138d40eb9da73796599c5026>:0)
UnityEngine.AndroidJNISafe.CallVoidMethod (System.IntPtr obj, System.IntPtr methodID, UnityEngine.jvalue[] args) (at <7c518b55138d40eb9da73796599c5026>:0)
UnityEngine.AndroidJavaObject._Call (System.String methodName, System.Object[] args) (at <7c518b55138d40eb9da73796599c5026>:0)
UnityEngine.AndroidJavaObject.Call (System.String methodName, System.Object[] args) (at <7c518b55138d40eb9da73796599c5026>:0)
GoogleMobileAds.Android.BannerClient.DestroyBannerView () (at <4d4765564a2844ea81a7d86659c37b5b>:0)
GoogleMobileAds.Api.BannerView.Destroy () (at <4d4765564a2844ea81a7d86659c37b5b>:0)

**Comment by rchallenger** [comment]
experiencing the same issue
#865

**Comment by rchallenger** [comment]
Just caught this exception on my device. It was after Purchasing AdsFree product, that disables active ads, prevents them from showing during current session and activating for further sessions.

**Comment by desouse** [comment]
Hello. I use v3.16 and face the same issue. Could you please tell me whether this bug is fixed or not in the latest release?

**Comment by awaisrajpoot** [comment]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.unity3d.services.banners.BannerView.load()' on a null object reference
        at com.unity3d.services.banners.UnityBanners$BannerAdRefreshView.reload(UnityBanners.java:295)
        at com.unity3d.services.banners.UnityBanners$BannerAdRefreshView.startReloadTask(UnityBanners.java:284)
        at com.unity3d.services.banners.UnityBanners$BannerAdRefreshView.access$400(UnityBanners.java:204)
        at com.unity3d.services.banners.UnityBanners$BannerAdRefreshView$3.onActivityResumed(UnityBanners.java:325)
        at android.app.Application.dispatchActivityResumed(Application.java:239)
        at android.app.Activity.onResume(Activity.java:1343)
        at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:456)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1412)
        at android.app.Activity.performResume(Activity.java:7292)

**Comment by stowy** [comment]
@awaisrajpoot that stack is from Unity Ads SDK and not from the Google Mobile Ads SDK.

I believe this issue is obsolete and will close it pending further reports.
